### ISSUE TITLE
Очікується що мають бути замінені стовбці але були замінені рядки

### ISSUE THREAD

**Issue by albussiverus** [MariiaSpiridonova/hillel_20231121#1]
https://github.com/MariiaSpiridonova/hillel_20231121/blob/e56e553c1215daec4912eaa30da8fa9e7bdc43b1/hw6/hw_6_2.py#L14

<img width="463" alt="image" src="https://github.com/MariiaSpiridonova/hillel_20231121/assets/142038191/2fe40e6f-30e5-4e05-9f47-b4183d186dd8">

<img width="303" alt="image" src="https://github.com/MariiaSpiridonova/hillel_20231121/assets/142038191/367cd260-3f2c-4850-a3ed-ea221dd2c82f">

**Comment by MariiaSpiridonova** [comment]
Corrected

**Comment by MariiaSpiridonova** [comment]
Correction was accepted
